package dotsync

import (
	"bytes"
	_ "embed"
	"os"
	"path/filepath"
)

// iconPNG is the dotsync app icon (generated by website/scripts/brand.mjs from assets/brand/).
//
//go:embed assets/icon.png
var iconPNG []byte

// installIcon writes the embedded icon to dotsync's data directory, so desktop notifications can
// show it, and returns its path ("" if it can't be written).
func installIcon() string {
	p := filepath.Join(NewPaths().DataDir, "icon.png")
	if cur, err := os.ReadFile(p); err == nil && bytes.Equal(cur, iconPNG) {
		return p
	}
	if err := atomicWrite(p, iconPNG, 0o644); err != nil {
		return ""
	}
	return p
}
