package dotsync

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The documentation site renders its command, secret-rule and default-value reference from
// website/src/data/reference.json, which this test generates from the code itself, so the two
// can't drift apart. After changing a command, flag, rule or default, regenerate it with:
//
//	go test ./internal/dotsync -run TestWebsiteReference -update-reference
var updateReference = flag.Bool("update-reference", false, "rewrite website/src/data/reference.json")

const referencePath = "../../website/src/data/reference.json"

type refFlag struct {
	Names   []string `json:"names"`             // e.g. ["-d", "--description"]
	Value   string   `json:"value,omitempty"`   // placeholder for the value; "" for a switch
	Repeats bool     `json:"repeats,omitempty"` // may be given more than once
	Default string   `json:"default,omitempty"`
	Usage   string   `json:"usage"`
}

type refCommand struct {
	Name    string    `json:"name"`
	Aliases []string  `json:"aliases,omitempty"`
	Args    string    `json:"args,omitempty"` // as in `dotsync help`
	Usage   string    `json:"usage"`          // as in `dotsync help <command>`
	Summary string    `json:"summary"`
	Flags   []refFlag `json:"flags"`
}

type refGroup struct {
	Title    string       `json:"title"`
	Commands []refCommand `json:"commands"`
}

type refContentRule struct {
	Name    string `json:"name"`
	Pattern string `json:"pattern"`
}

type reference struct {
	Comment  string     `json:"//"`
	Commands []refGroup `json:"commands"`
	Secrets  struct {
		Paths       []string         `json:"paths"`
		Content     []refContentRule `json:"content"`
		AllowMarker string           `json:"allow_marker"`
	} `json:"secrets"`
	DefaultIgnore []string    `json:"default_ignore"`
	SupportedOS   []string    `json:"supported_os"`
	GitSettings   [][2]string `json:"git_settings"`
	Defaults      struct {
		Interval            int    `json:"interval"`
		BackupRetentionDays int    `json:"backup_retention_days"`
		MaxFileSizeMiB      int    `json:"max_file_size_mib"`
		PushAttempts        int    `json:"push_attempts"`
		AgentLabel          string `json:"agent_label"`
		CronTag             string `json:"cron_tag"`
	} `json:"defaults"`
}

// commandFlags runs a command with -h and records the flags it defines, without running it.
func commandFlags(t *testing.T, cmd command) (string, []refFlag) {
	var fs *flag.FlagSet
	var usage string
	flagSetHook = func(f *flag.FlagSet, args string) { fs, usage = f, args }
	defer func() { flagSetHook = nil }()
	if _, err := cmd.run([]string{"-h"}, io.Discard, io.Discard); !errors.Is(err, flag.ErrHelp) {
		t.Fatalf("%s -h: expected help, got %v", cmd.name, err)
	}
	if fs == nil {
		t.Fatalf("%s defines no flag set", cmd.name)
	}
	var flags []refFlag
	aliasOf := map[string][]string{}
	fs.VisitAll(func(f *flag.Flag) {
		if target, ok := strings.CutPrefix(f.Usage, "same as -"); ok {
			aliasOf[target] = append(aliasOf[target], f.Name)
		}
	})
	fs.VisitAll(func(f *flag.Flag) {
		if strings.HasPrefix(f.Usage, "same as -") {
			return
		}
		rf := refFlag{Names: []string{dashes(f.Name)}}
		for _, a := range aliasOf[f.Name] {
			rf.Names = append(rf.Names, dashes(a))
		}
		name, u := flag.UnquoteUsage(f)
		rf.Usage = u
		if b, ok := f.Value.(interface{ IsBoolFlag() bool }); !ok || !b.IsBoolFlag() {
			rf.Value = name
			_, rf.Repeats = f.Value.(*stringList)
			if f.DefValue != "" && f.DefValue != "0" {
				rf.Default = f.DefValue
			}
		}
		flags = append(flags, rf)
	})
	if flags == nil {
		flags = []refFlag{}
	}
	return usage, flags
}

// dashes writes a flag the way the documentation does: -x for one letter, --name otherwise.
func dashes(name string) string {
	if len(name) == 1 {
		return "-" + name
	}
	return "--" + name
}

func buildReference(t *testing.T) []byte {
	t.Setenv("DOTSYNC_HOSTNAME", "<host>")
	var ref reference
	ref.Comment = "Generated by internal/dotsync/reference_test.go. Do not edit; run: go test ./internal/dotsync -run TestWebsiteReference -update-reference"
	for _, g := range commandGroups {
		rg := refGroup{Title: g.title}
		for _, cmd := range g.commands {
			usage, flags := commandFlags(t, cmd)
			rg.Commands = append(rg.Commands, refCommand{
				Name: cmd.name, Aliases: cmd.aliases, Args: cmd.args,
				Usage: strings.TrimSpace("dotsync " + cmd.name + " " + usage), Summary: cmd.summary, Flags: flags,
			})
		}
		ref.Commands = append(ref.Commands, rg)
	}
	ref.Secrets.Paths = secretPaths
	for _, r := range secretContent {
		ref.Secrets.Content = append(ref.Secrets.Content, refContentRule{r.name, r.re.String()})
	}
	ref.Secrets.AllowMarker = string(allowMarker)
	ref.DefaultIgnore = defaultIgnore
	ref.SupportedOS = supportedOS
	ref.GitSettings = repoSettings()
	ref.Defaults.Interval = defaultInterval
	ref.Defaults.BackupRetentionDays = defaultBackupRetentionDays
	ref.Defaults.MaxFileSizeMiB = maxFileSize >> 20
	ref.Defaults.PushAttempts = pushAttempts
	ref.Defaults.AgentLabel = agentLabel
	ref.Defaults.CronTag = cronTag

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(ref); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func TestWebsiteReference(t *testing.T) {
	want := buildReference(t)
	if *updateReference {
		if err := os.MkdirAll(filepath.Dir(referencePath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(referencePath, want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(referencePath)
	if err != nil {
		t.Fatalf("%v; generate it with: go test ./internal/dotsync -run TestWebsiteReference -update-reference", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s is out of date; regenerate it with: go test ./internal/dotsync -run TestWebsiteReference -update-reference", referencePath)
	}
}
