#!/bin/sh
# Prints the Homebrew formula for a release, using the prebuilt archives listed in its
# checksums.txt. The release workflow publishes it to the tap (vars.HOMEBREW_TAP); CI installs
# and tests it against a snapshot build.
#
#   packaging/homebrew/formula.sh <version> <checksums.txt> [base-url]
#
# base-url is where the archives are downloaded from; by default the GitHub release.
#
# A formula rather than a cask: casks are for macOS apps, and quarantine their downloads, which
# Gatekeeper then blocks because the binary isn't notarized. Formulae also work on Linux.
set -eu

version=${1#v}
checksums=$2
base=${3:-https://github.com/pungoyal/dotsync/releases/download/v$version}

sum() {
	name="dotsync_${version}_$1.tar.gz"
	s=$(awk -v n="$name" '$2 == n { print $1 }' "$checksums")
	[ -n "$s" ] || { echo "error: $name is not in $checksums" >&2; exit 1; }
	printf '%s' "$s"
}

block() {
	cat <<RUBY
      url "$base/dotsync_${version}_$1.tar.gz"
      sha256 "$(sum "$1")"
RUBY
}

cat <<RUBY
# Generated by packaging/homebrew/formula.sh in https://github.com/pungoyal/dotsync.
# Every release replaces this file; changes made here are lost.
class Dotsync < Formula
  desc "Set-and-forget dotfile sync for macOS and Linux"
  homepage "https://pungoyal.github.io/dotsync/"
  version "$version"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
$(block darwin_arm64)
    end
    on_intel do
$(block darwin_amd64)
    end
  end

  on_linux do
    on_arm do
$(block linux_arm64)
    end
    on_intel do
$(block linux_amd64)
    end
  end

  def install
    bin.install "dotsync"
    man1.install "manpages/dotsync.1.gz"
  end

  def caveats
    <<~EOS
      Homebrew keeps dotsync up to date: use \`brew upgrade dotsync\` instead of \`dotsync update\`.
      To get started: dotsync init <git-url>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dotsync version")

    # A full round trip: set up against a local remote, manage a file, check it was pushed.
    system "git", "init", "--quiet", "--bare", "remote.git"
    (testpath/".testrc").write "hello\\n"
    system bin/"dotsync", "init", "--no-agent", "--no-install", "file://#{testpath}/remote.git"
    system bin/"dotsync", "add", testpath/".testrc"
    assert_equal "hello\\n", shell_output("git -C remote.git show main:files/testrc")
  end
end
RUBY
